name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build
        run: |
          npm install
          npm run-script build
        env:
          REACT_APP_API: ${{secrets.REACT_APP_API}}
          REACT_APP_BASENAME: ${{secrets.REACT_APP_BASENAME}}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
